// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appRoot': string;
  'buttonNotAvailable': string;
  'gameRoomControls': string;
  'gameRoomPlayer': string;
  'gameRoomPlayerCard': string;
  'gameRoomPlayerCardOpen': string;
  'gameRoomPlayerCards': string;
  'gameRoomPlayerName': string;
  'gameRoomPlayers': string;
  'gameRoomResult': string;
  'gameRoomResultName': string;
  'gameRoomResultRank': string;
  'gameRoomResults': string;
  'notAvailable': string;
  'overlay': string;
  'overlayMessage': string;
  'sceneMain': string;
  'sceneTitle': string;
  'select': string;
  'selectItem': string;
  'selectItemActive': string;
  'textInput': string;
  'waitRoomPlayer': string;
  'waitRoomPlayerName': string;
  'waitRoomPlayerNotReady': string;
  'waitRoomPlayerReady': string;
}
export const cssExports: CssExports;
export default cssExports;
